// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Solo cargar dotenv en desarrollo. En producción (Docker/Dokploy) las variables
// ya están disponibles en process.env y no necesitamos el archivo .env
import { existsSync } from "fs";
import { config } from "dotenv";

// Solo cargar .env si existe (desarrollo local)
if (existsSync(".env")) {
  config();
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
